---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
  - name: Update apt cache.
    apt: update_cache=true cache_valid_time=600
    when: ansible_os_family == 'Debian'

  roles:
  - role: xat59.sftp

  post_tasks:
  - name: Ensure default SFTP group exists
    group:
      name: sftpusers
      state: present
