---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
  - name: Update apt cache.
    apt: update_cache=true cache_valid_time=600
    when: ansible_os_family == 'Debian'

  - name: Install SSH server
    apt: name=openssh-server
    when: ansible_os_family == 'Debian'

  - name: Install SSH server
    yum: name=openssh-server
    when: ansible_os_family == 'RedHat'

  roles:
    - role: xat59.sftp
      vars:
        sftp_users:
          - name: c1111
            password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass
            shell: false
            append: true
            group: sftpusers

  post_tasks:
    - name: Ensure default SFTP group exists
      group:
        name: sftpusers
        state: present
